import { useState, useCallback } from 'react';
import { FileText, Download, Loader2 } from 'lucide-react';
import type { WorkflowSession } from '../../types/workflow';

interface PDFExportProps {
  session: WorkflowSession;
  workflowTitle: string;
}

export function PDFExport({ session, workflowTitle }: PDFExportProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const generatePDF = useCallback(async () => {
    setIsGenerating(true);
    setError(null);

    try {
      // Dynamic import to reduce initial bundle size
      const { jsPDF } = await import('jspdf');

      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a4',
      });

      // Colors
      const primaryColor = '#B45309';
      const textColor = '#78350F';
      const lightColor = '#FEF3E2';

      // Header
      doc.setFillColor(lightColor);
      doc.rect(0, 0, 210, 40, 'F');

      doc.setFont('helvetica', 'bold');
      doc.setFontSize(24);
      doc.setTextColor(primaryColor);
      doc.text('Daraja', 20, 25);

      doc.setFontSize(14);
      doc.setFont('helvetica', 'normal');
      doc.text(workflowTitle, 20, 35);

      // Metadata
      doc.setFontSize(10);
      doc.setTextColor(textColor);
      const dateStr = new Date(session.startedAt).toLocaleDateString();
      doc.text(`Session ID: ${session.id}`, 140, 25);
      doc.text(`Date: ${dateStr}`, 140, 32);

      // Content
      let yPos = 55;
      const leftMargin = 20;
      const contentWidth = 170;
      const lineHeight = 7;

      doc.setFontSize(12);

      // Group responses by section (simplified)
      for (const [fieldId, response] of Object.entries(session.responses)) {
        if (yPos > 270) {
          doc.addPage();
          yPos = 20;
        }

        // Field label
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(primaryColor);
        doc.text(fieldId.replace(/([A-Z])/g, ' $1').trim(), leftMargin, yPos);
        yPos += lineHeight;

        // Original response
        doc.setFont('helvetica', 'normal');
        doc.setTextColor(textColor);

        const originalText = String(response.value);
        const originalLines = doc.splitTextToSize(originalText, contentWidth);
        doc.text(originalLines, leftMargin, yPos);
        yPos += originalLines.length * lineHeight + 2;

        // Translation if available
        const translation = session.translations[fieldId];
        if (translation) {
          doc.setFillColor(lightColor);
          doc.rect(leftMargin - 2, yPos - 4, contentWidth + 4, 8 + lineHeight, 'F');

          doc.setFont('helvetica', 'italic');
          const translatedLines = doc.splitTextToSize(
            translation.translatedText,
            contentWidth - 10
          );
          doc.text(translatedLines, leftMargin + 5, yPos);
          yPos += translatedLines.length * lineHeight + 5;

          // Confidence indicator
          const confidenceColor =
            translation.confidence >= 0.8
              ? '#16A34A'
              : translation.confidence >= 0.5
              ? '#D97706'
              : '#DC2626';
          doc.setTextColor(confidenceColor);
          doc.setFontSize(8);
          doc.text(
            `Confidence: ${Math.round(translation.confidence * 100)}%`,
            leftMargin + 5,
            yPos - 2
          );
          doc.setFontSize(12);
        }

        yPos += 10;
      }

      // Footer on each page
      const pageCount = doc.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(textColor);
        doc.text(
          `Page ${i} of ${pageCount} | Generated by Daraja`,
          105,
          290,
          { align: 'center' }
        );
      }

      // Save
      const filename = `daraja-${session.workflowType}-${session.id.slice(-8)}.pdf`;
      doc.save(filename);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to generate PDF');
    } finally {
      setIsGenerating(false);
    }
  }, [session, workflowTitle]);

  return (
    <div className="space-y-4">
      <button
        onClick={generatePDF}
        disabled={isGenerating}
        className="btn-primary w-full"
      >
        {isGenerating ? (
          <>
            <Loader2 className="w-5 h-5 mr-2 animate-spin" />
            Generating PDF...
          </>
        ) : (
          <>
            <Download className="w-5 h-5 mr-2" />
            Export Bilingual PDF
          </>
        )}
      </button>

      {error && (
        <p className="text-sm text-alert-500 text-center">{error}</p>
      )}

      <p className="text-xs text-daraja-400 text-center">
        PDF includes both original responses and translations with confidence indicators.
      </p>
    </div>
  );
}
